### ISSUE TITLE
Problem to installbotstraap 

### ISSUE THREAD

**Issue by Necrolinkwire** [hacks-guide/Guide_3DS#1917] opened 2021-09-12 16:48 UTC
![IMG_0298](https://user-images.githubusercontent.com/90569508/132995919-99d8cb1b-4841-438a-86ac-564c2f64978b.PNG)

**Comment by lifehackerhansol** [comment] 2021-09-12 16:59
Duplicate of https://github.com/hacks-guide/Guide_3DS/issues/1916.

**Comment by lilyuwuu** [comment] 2021-09-12 18:22
Closed, duplicate/invalid

**Closed by lilyuwuu** 2021-09-12 18:22 UTC
