### ISSUE TITLE
Browserhax crashes the Internet Browser to Home menu

### ISSUE THREAD

**Issue by Tendali** [hacks-guide/Guide_3DS#1800] opened 2020-10-26 08:16 UTC
During my installation of CWF, I encountered an issue where after pressing the button on https://zoogie.github.io/web/nbhax/, the browser crashed to home menu with the message: "An error has occurred. Please save your data in any software currently in use, and then restart the system."
The guide instructed me to retry, but to no avail.

The solution for me was to clear the cache of the browser and set it up again. As said in this thread: https://gbatemp.net/threads/browserhax-not-working.414015/

**Comment by lilyuwuu** [comment] 2020-10-26 09:21
We're already aware of the meaning of different ways browserhax will fail -- see here for a list: https://3ds.eiphax.tech/issues

Because this case isn't from user error, it is important to add it to the main page. Maybe `If the console shows "An error has occurred", clear cache and try again`? (While crashes can be caused by user error, the guide has to assume that no user error is happening. Saying "crashes without a coloured screen" seems unnecessarily confusing IMO.)

The thread you linked is from 2016 -- it just so happens that the solution is the same.

**Comment by Tendali** [comment] 2020-10-29 14:30
Thanks. I do agree that there should be a link to the Issues page, since the page only accounts for a crash "on a yellow screen" and I am pretty sure that I didn't miss a step in the process. (Although I did have CFW on my 3ds before, but I removed it. So maybe some "residue" from my previous installation was causing the issue.)

**Comment by lilyuwuu** [comment] 2020-10-31 00:03
Resolved in [this commit](https://github.com/hacks-guide/Guide_3DS/commit/392b80eec5899bc2f2d2db041880d6a2f97cdc9d)

**Closed by lilyuwuu** 2020-10-31 00:03 UTC
